version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(deps)'
    groups:
      all:
        patterns:
          - '*'
